src/main/java/edu/ucsb/cs156/example/ExampleApplication.java
src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
src/main/java/edu/ucsb/cs156/example/repositories/MenuItemReviewRepository.java
src/main/resources/db/migration/changes/MenuItemReview.json

Adding Entity, Repository, and Database Migration for MenuItemReviews. 
Closes #26

Create database table for MenuItemReview

---

src/main/java/edu/ucsb/cs156/example/entities/Articles.java
src/main/java/edu/ucsb/cs156/example/repositories/ArticlesRepository.java
src/main/resources/db/migration/changes/Articles.json

Added entity, repository, and database file for Articles
Closes #38

Articles Database creation

---

src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json

Passed all acceptance criteria for the database issue for UCSBDiningCommonsMenu
Closes #8

UCSBDiningCommonsMenu Database Issue

---

src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/main/resources/db/migration/changes/HelpRequests.json

Added the Help requests table into the database
Closes #32

Help Request Database Creation

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestsController.java
src/main/java/edu/ucsb/cs156/example/entities/HelpRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/HelpRequestRepository.java
src/main/resources/db/migration/changes/HelpRequests.json
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestsControllerTests.java

Created HelpRequests Controller and add /all and /post endpoints.
Added test cases for /all and /post endpoints
Closes #33

Create HelpRequests Controller with /all and /post endpoints

---

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/resources/db/migration/changes/MenuItemReview.json
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Added GET and POST endpoints for Menu Item Review Controller and tests.
Closes #27

Create Menu Item Review Controller

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Added GET and POST endpoints for Articles controller and added tests.
Closes #39

Articles Controller and Tests

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Added DELETE endpoint to Articles Controller and added tests.
Closes #42

Articles Controller DELETE endpoint

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestsController.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestsControllerTests.java

Added HelpRequest GET (show) endpoint and corresponding test cases.
Closes #34

Add HelpRequest GET (show) endpoint and test cases

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Added PUT endpoint to Articles Controller and added tests.
Closes #41

Articles Controller PUT endpoint

---

src/main/java/edu/ucsb/cs156/example/controllers/HelpRequestsController.java
src/test/java/edu/ucsb/cs156/example/controllers/HelpRequestsControllerTests.java

Added HelpRequest PUT Endpoint and test cases.
Fixed some method name typos in HelpRequestController.
Closes #35

Add HelpRequest PUT Endpoint

---

src/main/java/edu/ucsb/cs156/example/entities/UCSBOrganization.java
src/main/java/edu/ucsb/cs156/example/repositories/UCSBOrganizationRepository.java
src/main/resources/db/migration/changes/UCSBOrganization.json

Added the UCSB Organizations table into the database
closes #14

Organizations Database Creation

---

src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
src/test/java/edu/ucsb/cs156/example/controllers/ArticlesControllerTests.java

Added GET endpoint to articles controller and tests
Closes #40

Articles Controller GET endpoint

---

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/resources/db/migration/changes/MenuItemReview.json
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Adding Menu Item Review GET endpoint and tests.
Closes #28

Create Menu Item Review GET

---

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/main/resources/db/migration/changes/MenuItemReview.json
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Adding Menu Item Review DELETE endpoint and tests.
Closes #30

Create Menu Item Review DELETE

---

src/main/java/edu/ucsb/cs156/example/controllers/MenuItemReviewController.java
src/test/java/edu/ucsb/cs156/example/controllers/MenuItemReviewControllerTests.java

Adding Menu Item Review PUT endpoint and tests.
Closes #29

Create Menu Item Review PUT

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/main/resources/db/migration/changes/UCSBDiningCommonsMenuItem.json
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

- Implemented post and all endpoints
- Passed all test cases
- 100% test coverage
- 100% mutations passed
Closes #9

Anderson Controller

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

- implemented get endpoint
- tests all pass
- 100% coverage
- 100% mutation tests pass
Closes #10

Implemented get endpoint and tests for menu items

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationControllerTests.java

Finished get,put,delete controller functions and tested with 100% coverage
closes #15 #16 #17 #18

ADD DELETE, GET, PUT endpoint for UCSBOrganization Controller

---

src/main/java/edu/ucsb/cs156/example/controllers/RecommendationRequestController.java
src/main/java/edu/ucsb/cs156/example/entities/RecommendationRequest.java
src/main/java/edu/ucsb/cs156/example/repositories/RecommendationRequestRepository.java
src/main/resources/db/migration/changes/RecommendationRequest.json
src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestControllerTests.java

In this PR, added all the endpoints for GET, DELETE, and PUT. Test cases was also included for each method. Tested on swagger and all methods were working correctly.  
Closes #20, closes #21, closes #22, closes #23, closes #24

Jaren-Controller Added All Methods 

---

src/main/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemController.java
src/test/java/edu/ucsb/cs156/example/controllers/UCSBDiningCommonsMenuItemControllerTests.java

Implemented DEL endpoint for menu items passed all tests
Closes #12

Implemented DEL endpoint 
